services:
  mongodb:
    container_name: mongodb
    networks:
      - cdp-network
    image: mongo:6.0.13
    volumes:
      - ./ssl:/etc/ssl:ro
    command: [
      "--tlsMode", "requireTLS",
      "--tlsCertificateKeyFile", "/etc/ssl/mongodb.pem"
    ]
  service:
    build:
      context: ../..
    container_name: cdp-java-backend-template
    image: cdp-java-backend-template
    networks:
      - cdp-network
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      PORT: 8085
      SERVICE_VERSION: 0.0.0-local
      ENVIRONMENT: local
      MONGO_URI: mongodb://mongodb:27017/?ssl=true
      MONGO_DATABASE: cdp-java-backend-template
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      METRICS_ENABLED: false
      TRUSTSTORE_CDP_ROOT_CA: ${MONGODB_TEST_CA_PEM}

networks:
  cdp-network:
    driver: bridge